[versions]
agp = "8.9.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
activity = "1.3.1"
constraintlayout = "2.1.0"
espressoContrib = "3.7.0"
uiautomator = "2.3.0"
guava = "32.1.3-android"
workRuntimeKtx = "2.9.0"
gridlayout = "1.0.0"
room = "2.6.1"
mpandroidchart = "v3.1.0"
biometric = "1.2.0"
testRunner = "1.5.2"
testCore = "1.5.0"
materialVersion = "1.12.0"
cardview = "1.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espressoContrib" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
material-v1120 = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
